source 'https://rubygems.org'

gem 'brakeman', require: false
gem 'bundler', require: false
gem 'debug', require: false
gem 'kamal', require: false
gem 'minitest', require: false
gem 'rails', require: false
gem 'rbi', require: false
gem 'rbs', require: false
gem 'rbs-inline', require: false
gem 'ruby-lsp', require: false
gem 'rubocop', require: false
gem 'rubocop-minitest', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', require: false
gem 'spreen-clean', require: false
gem 'spreen-pr', require: false
gem 'spreen-tracks', require: false
gem 'spreen-wiki', require: false
gem 'steep', require: false
gem 'sorbet', require: false
gem 'tapioca', require: false
gem 'typeprof', require: false
